'use client';

import { useEffect, useState } from 'react';

interface BriefRecord {
  brief_date: string;
  convergence_phase: string;
  convergence_index: number;
  risk_level: string;
  capital_window: string;
  narrative: string;
  claims_count: number;
  docs_count: number;
  pdf_url: string | null;
  created_at: string;
}

const PHASE_STYLE: Record<string, string> = {
  Monitoring:   'bg-zinc-500/20 text-zinc-400',
  Building:     'bg-blue-500/20 text-blue-400',
  Accelerating: 'bg-amber-500/20 text-amber-400',
  Critical:     'bg-emerald-500/20 text-emerald-300',
};

const RISK_STYLE: Record<string, string> = {
  Minimal:  'text-emerald-400',
  Low:      'text-green-400',
  Moderate: 'text-amber-400',
  High:     'text-red-400',
};

export default function ReportsPage() {
  const [reports, setReports] = useState<BriefRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch('/api/reports')
      .then(r => {
        if (!r.ok) throw new Error(`${r.status}`);
        return r.json();
      })
      .then(setReports)
      .catch(e => setError(e.message))
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <div className="p-8 flex items-center justify-center min-h-[50vh]">
        <div className="animate-pulse text-zinc-500 text-sm">Loading report archive…</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-8">
        <div className="bg-red-900/20 border border-red-800 rounded-xl p-6 text-red-400 text-sm">
          Failed to load reports: {error}
        </div>
      </div>
    );
  }

  return (
    <div className="p-6 space-y-6 max-w-[1100px] mx-auto">
      <header className="border-b border-zinc-800 pb-4">
        <h1 className="text-2xl font-extrabold tracking-tight text-zinc-100">
          Intelligence Report Archive
        </h1>
        <p className="text-sm text-zinc-500 mt-1">
          Daily briefs generated by the DICS intelligence pipeline
        </p>
      </header>

      {reports.length === 0 ? (
        <div className="bg-zinc-950 border border-zinc-800 rounded-xl p-8 text-center">
          <p className="text-sm text-zinc-500">No reports generated yet.</p>
          <p className="text-xs text-zinc-600 mt-1">
            Reports are automatically generated daily at 06:30 UTC.
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {reports.map(r => (
            <ReportRow key={r.brief_date} report={r} />
          ))}
        </div>
      )}
    </div>
  );
}

function ReportRow({ report }: { report: BriefRecord }) {
  const d = new Date(report.brief_date + 'T12:00:00Z');
  const dayLabel = d.toLocaleDateString('en-US', {
    weekday: 'short',
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });

  const phaseStyle = PHASE_STYLE[report.convergence_phase] ?? 'bg-zinc-500/20 text-zinc-400';
  const riskStyle = RISK_STYLE[report.risk_level] ?? 'text-zinc-400';

  return (
    <div className="bg-zinc-950 border border-zinc-800 rounded-xl p-5 hover:border-zinc-700 transition-colors">
      <div className="flex items-start justify-between gap-4">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-3 mb-2">
            <span className="text-sm font-bold text-zinc-100">{dayLabel}</span>
            <span className={`px-2 py-0.5 rounded-full text-[10px] font-semibold uppercase tracking-wider ${phaseStyle}`}>
              {report.convergence_phase}
            </span>
            <span className={`text-xs font-mono ${riskStyle}`}>
              Risk: {report.risk_level}
            </span>
          </div>
          <p className="text-xs text-zinc-400 line-clamp-2 leading-relaxed">
            {report.narrative}
          </p>
          <div className="flex items-center gap-4 mt-2 text-[10px] text-zinc-600">
            <span>{report.docs_count} docs</span>
            <span>{report.claims_count} claims</span>
            <span>Convergence: {Math.round(report.convergence_index)}/100</span>
            <span>Window: {report.capital_window}</span>
          </div>
        </div>
        <div className="flex items-center gap-2 shrink-0">
          <a
            href={`/console/brief`}
            className="px-3 py-1.5 text-xs font-medium text-zinc-300 border border-zinc-700 rounded-lg hover:bg-zinc-800 transition-colors"
          >
            View
          </a>
          {report.pdf_url && (
            <a
              href={report.pdf_url}
              target="_blank"
              rel="noopener noreferrer"
              className="px-3 py-1.5 text-xs font-medium text-gold border border-gold/30 rounded-lg hover:bg-gold/10 transition-colors"
            >
              PDF ↓
            </a>
          )}
        </div>
      </div>
    </div>
  );
}
